[package]
name = "ndkarte"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
log = "0.4"
android_logger = "0.14"
gpx = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
